modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPLv3"

[[mods]]
modId = "dynamicjs"
version = "${version}"
displayName = "DynamicJS"
logoFile = "icon.png"
authors = "Prunoideae"

description = '''
Doing subclassing dynamically via bytecode hacks
'''

[[dependencies.dynamicjs]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynamicjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
